Fix examples compatibility with Color-0.2.0 and massiv-io-0.3.0.1
This change fixes this example build failure:

  Error: While constructing the build plan, the following exceptions were encountered:

  In the dependencies for massiv-io-0.3.0.1:
    Color-0.1.4 from stack configuration does not match >=0.2  (latest matching version is 0.2.0)
  needed due to examples-0.1.0.0 -> massiv-io-0.3.0.1